[workspace]
resolver = "2"
members = [
    "loxi",
    "loxii",
]

[workspace.dependencies]
clap = { version = "4.5.17", features = ["derive"] }
coredump = "0.1.2"
thiserror = "1.0.63"
rustc-hash = "2.0.0"

pretty_assertions = "1.4.1"


[profile.release]
debug = 1
